dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

sources:
  - google-chrome
packages:
  - dpkg
  - google-chrome-stable
  - libgconf-2-4

cache:
  npm: true
  directories:
    - ./node_modules
    - ~/.cache

install:
  - npm ci

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run cypress:ci &
