dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

sources:
  - google-chrome
packages:
  - dpkg
  - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
